spring:
  application:
    name:
      greet-service

  boot:
    admin:
      client:
        url: http://localhost:1111

server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include: "*"

# optional of eureka server is running on 8761 otherwise required to register.
#eureka:
#  client:
#    service-url:
#      defaultZone:
#        http://localhost:8761/eureka/