spring:
  application:
    name:
      welcome-api

  boot:
    admin:
      client:
        url: http://localhost:1111

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details:always
# optional of eureka server is running on 8761 otherwise required to register.
#eureka:
#  client:
#    service-url:
#      defaultZone:
#        http://localhost:8761/eureka/